# Generated by Django 2.0.7 on 2018-08-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='foursquare_id',
            field=models.CharField(default='4b05886cf964a520fcc422e3', max_length=250),
            preserve_default=False,
        ),
    ]
