# Generated by Django 2.0.7 on 2018-08-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_location_foursquare_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position_lat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='position_lng',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
