# Generated by Django 2.0.7 on 2018-09-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180830_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
    ]
